apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: dhanuar/app:eks-app:0.0.2
      ports:
        - containerPort: 8080
